version: "2"
services: 
    web:
        build: .
        volumes:  
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        environment:  
            - PORT=8080
            - DATABASE_URI=mongodb://database:27017/                #here write name of other container(currently database)
            - DATABASE_NAME=CRUD_basic
        ports: 
            - "5000:8080"               #Container's port 5000 mapped to machine's port 8080
        depends_on: 
            - database
    database:
        image: 'mongo'
        environment : 
            - MONGO_INITDB_DATABASE="CRUD_basic"                                      #These 3 will give Unauthorized MongoError
            # - MONGO_INITDB_ROOT_USERNAME=root                         
            # - MONGO_INITDB_ROOT_PASSWORD=1010
            # - MONGODB_DATABASE="CRUD_basic"
            - MONGODB_ROOT_USERNAME=root
            - MONGODB_ROOT_PASSWORD=1010
        volumes:  
            - ./mongo-volume:/data/db
        ports:
            - '27019:27017'